#!/usr/bin/env python3
"""
assemble_book.py -- build book.tex from the standalone chapter files.

Mechanics:
  * preamble = documentclass/geometry/brumfiel (canonical) + every chapter's
    \\input{figuresNN} + every chapter's hoisted local-macro block
  * body     = frontmatter body (with the "% \\tableofcontents here." marker
    replaced by the real \\tableofcontents), then \\pagenumbering{arabic},
    then each chapter body, then the appendix
  * duplicate \\newcommand names across local blocks abort the build unless
    the definitions are textually identical (first one wins).

Run from the project root:  python3 tools/assemble_book.py
Then: tectonic -Z search-path=style -Z search-path=chapters --outdir build book.tex
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CH = os.path.join(ROOT, 'chapters')

UNITS = (['frontmatter'] + [f'ch{n:02d}' for n in range(1, 17)] + ['appendix'])

MARK_A = '% ---- local macros (hoist into book preamble) ----'
MARK_B = '% ---- end local macros ----'


def split_unit(name):
    src = open(os.path.join(CH, name + '.tex')).read()
    m = re.search(r'\\begin\{document\}(.*)\\end\{document\}', src, re.S)
    if not m:
        sys.exit(f'{name}: no document body found')
    body = m.group(1).strip('\n')
    pre = src[:m.start()]
    block = ''
    if MARK_A in pre:
        a = pre.index(MARK_A) + len(MARK_A)
        b = pre.index(MARK_B)
        block = pre[a:b].strip('\n')
    figs = re.findall(r'\\input\{(figures[0-9a-z]+)\}', pre)
    return figs, block, body


def main():
    fig_inputs, blocks, bodies = [], [], {}
    seen = {}
    for u in UNITS:
        figs, block, body = split_unit(u)
        for f in figs:
            if f not in fig_inputs:
                fig_inputs.append(f)
        if block:
            kept = []
            for mm in re.finditer(r'\\newcommand\{(\\[A-Za-z]+)\}', block):
                nm = mm.group(1)
                if nm in seen:
                    print(f'  note: {u}: {nm} already defined by {seen[nm]}; '
                          'keeping the first definition')
                else:
                    seen[nm] = u
                    kept.append(nm)
            blocks.append((u, block, kept))
        bodies[u] = body

    # drop duplicate \newcommand lines: comment out redefinitions wholesale is
    # risky; instead abort if a duplicate name has a DIFFERENT definition.
    defs = {}
    for u, block, kept in blocks:
        for mm in re.finditer(
                r'\\newcommand\{(\\[A-Za-z]+)\}.*?(?=(?:\\newcommand\{)|\Z)',
                block, re.S):
            nm = mm.group(1)
            txt = re.sub(r'\s+', ' ', mm.group(0)).strip()
            if nm in defs and defs[nm][1] != txt:
                sys.exit(f'CONFLICT: {nm} defined differently in '
                         f'{defs[nm][0]} and {u} -- resolve before assembly')
            defs.setdefault(nm, (u, txt))

    out = []
    out.append('% book.tex -- generated by tools/assemble_book.py; edit the')
    out.append('% chapter files, not this file, then re-run the assembler.')
    out.append('\\documentclass[11pt]{book}')
    out.append('\\usepackage[paperwidth=145mm,paperheight=200mm,'
               'top=18mm,bottom=20mm,inner=20mm,outer=16mm]{geometry}')
    out.append('\\usepackage{brumfiel}')
    for f in fig_inputs:
        out.append('\\input{' + f + '}')
    emitted = set()
    for u, block, kept in blocks:
        lines = []
        skip = False
        for ln in block.split('\n'):
            mm = re.match(r'\\newcommand\{(\\[A-Za-z]+)\}', ln)
            if mm:
                skip = mm.group(1) in emitted
                if not skip:
                    emitted.add(mm.group(1))
            if not skip:
                lines.append(ln)
        if any(l.strip() and not l.strip().startswith('%') for l in lines):
            out.append(f'% ================= local macros from {u} =================')
            out.extend(lines)
    out.append('% short pages end short instead of stretching inter-para glue')
    out.append('\\raggedbottom')
    out.append('% several units relied on standalone-body emergencystretch; the')
    out.append('% narrow 145mm measure needs it book-wide (appendix flag, 2026-08-17)')
    out.append('\\emergencystretch=2em')
    out.append('\\begin{document}')
    fm = bodies['frontmatter'].replace('% \\tableofcontents here.',
                                       '\\tableofcontents')
    if '\\tableofcontents' not in fm:
        sys.exit('frontmatter: tableofcontents marker not found')
    out.append(fm)
    out.append('\\cleardoublepage\n\\pagenumbering{arabic}')
    # Standalone chapter docs start with fresh counters; the merged book must
    # reset them by hand because \chapter* never steps the chapter counter.
    RESETS = ('\\setcounter{theorem}{0}\\setcounter{definition}{0}'
              '\\setcounter{construction}{0}\\setcounter{exgroup}{0}'
              '\\setcounter{footnote}{0}')
    for u in UNITS[1:]:
        out.append(f'% ==================== {u} ====================')
        out.append(RESETS)
        out.append(bodies[u])
        out.append('\\clearpage')
    out.append('\\end{document}')
    open(os.path.join(ROOT, 'book.tex'), 'w').write('\n'.join(out) + '\n')
    print(f'book.tex written: {len(fig_inputs)} figure files, '
          f'{len(blocks)} local-macro blocks, {len(UNITS)} units')


if __name__ == '__main__':
    main()
