#!/usr/bin/env python3
"""Guard the minimum clear gap in the dense Chapter 6 multipart angle plates.

The whole-book candidate set is rendered by ``audit_multipart_figures.py`` for
visual review.  These are the same-coordinate-system plates where a later edit
could silently pull independent drawings back together, so their panel limits
are also checked numerically here.  Geometry is expressed in the unscaled TikZ
coordinate system; the drawings retain their existing scale.
"""

from __future__ import annotations

import os
import re
import sys


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "chapters", "figures06.tex")
MIN_GAP_CM = 0.80


def macro_chunk(source: str, name: str) -> str:
    start = source.index(r"\newcommand{" + name + "}")
    next_macro = source.find(r"\newcommand{\FIG", start + 1)
    return source[start:next_macro if next_macro >= 0 else len(source)]


def shifted_scopes(chunk: str) -> list[float]:
    return [float(value) for value in re.findall(r"\\begin\{scope\}\[xshift=([0-9.]+)cm", chunk)]


def coordinate_xs(chunk: str, point: str) -> list[float]:
    pattern = rf"\\coordinate \({re.escape(point)}\)\s+at \(([0-9.]+),"
    return [float(value) for value in re.findall(pattern, chunk)]


def require_gap(issues: list[str], figure: str, left_max: float, right_min: float):
    gap = right_min - left_max
    if gap + 1e-9 < MIN_GAP_CM:
        issues.append(f"{figure}: {gap:.2f} cm clear; requires {MIN_GAP_CM:.2f} cm")
    else:
        print(f"PASS {figure}: {gap:.2f} cm")


def main():
    source = open(SOURCE, encoding="utf-8").read()
    issues: list[str] = []

    # 6-69: three proof panels, each with a 1.92 cm horizontal footprint.
    shifts = shifted_scopes(macro_chunk(source, r"\FIGVISIXTYNINE"))
    if len(shifts) != 2:
        issues.append("6-69: expected two shifted scopes")
    else:
        require_gap(issues, "6-69 a/b", 1.92, shifts[0])
        require_gap(issues, "6-69 b/c", shifts[0] + 1.92, shifts[1])

    # 6-71: two arrowhead constructions; the first reaches x=1.58.
    shifts = shifted_scopes(macro_chunk(source, r"\FIGVISEVENTYONE"))
    if len(shifts) != 1:
        issues.append("6-71: expected one shifted scope")
    else:
        require_gap(issues, "6-71 a/b", 1.58, shifts[0])

    # 6-93: three cases generated by one foreach; each line spans -0.28..1.86.
    chunk = macro_chunk(source, r"\FIGVININETYTHREE")
    match = re.search(r"\\foreach \\dx/\\ax/\\ay in \{([^}]+)\}", chunk)
    if not match:
        issues.append("6-93: panel foreach not found")
    else:
        origins = [float(item.split("/")[0]) for item in match.group(1).split(",")]
        if len(origins) != 3:
            issues.append("6-93: expected three panel origins")
        else:
            require_gap(issues, "6-93 a/b", origins[0] + 1.86, origins[1] - 0.28)
            require_gap(issues, "6-93 b/c", origins[1] + 1.86, origins[2] - 0.28)

    # 6-94: panel footprints are [-.12,1.96], [-.12,1.92], and [.02,2.76].
    shifts = shifted_scopes(macro_chunk(source, r"\FIGVININETYFOUR"))
    if len(shifts) != 2:
        issues.append("6-94: expected two shifted scopes")
    else:
        require_gap(issues, "6-94 a/b", 1.96, shifts[0] - 0.12)
        require_gap(issues, "6-94 b/c", shifts[0] + 1.92, shifts[1] + 0.02)

    # 6-98 through 6-101: in each half the first angle ends at A (x=2.30)
    # and the independent comparison angle begins at Lb.
    for macro, figures in [
        (r"\FIGVININETYEIGHTNINETYNINE", ("6-98", "6-99")),
        (r"\FIGVIONEHUNDREDONEHUNDREDONE", ("6-100", "6-101")),
    ]:
        left_edges = coordinate_xs(macro_chunk(source, macro), "Lb")
        if len(left_edges) != 2:
            issues.append(f"{figures[0]}/{figures[1]}: expected two Lb coordinates")
        else:
            for figure, right_min in zip(figures, left_edges):
                require_gap(issues, figure, 2.30, right_min)

    # 6-103: first two panels span -.02..1.92; the third spans .02..2.34.
    shifts = shifted_scopes(macro_chunk(source, r"\FIGVIONEHUNDREDTHREE"))
    if len(shifts) != 2:
        issues.append("6-103: expected two shifted scopes")
    else:
        require_gap(issues, "6-103 a/b", 1.92, shifts[0] - 0.02)
        require_gap(issues, "6-103 b/c", shifts[0] + 1.92, shifts[1] + 0.02)

    # 6-104 already has a wider gap, but keep it in the guard because it is
    # the next two-case angle plate and should follow the same convention.
    shifts = shifted_scopes(macro_chunk(source, r"\FIGVIONEHUNDREDFOUR"))
    if len(shifts) != 1:
        issues.append("6-104: expected one shifted scope")
    else:
        require_gap(issues, "6-104 a/b", 1.82, shifts[0] + 0.02)

    if issues:
        print("\nFAIL multipart spacing:")
        for issue in issues:
            print(f"  {issue}")
        sys.exit(1)
    print(f"\nAll guarded multipart panels meet the {MIN_GAP_CM:.2f} cm minimum.")


if __name__ == "__main__":
    main()
